name: Deploy to GCP VM

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 의존성 설치
      - name: Install dependencies
        run: npm ci

      # 3. .env 파일 생성
      - name: Create .env file
        run: |
          touch .env
              echo "KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }}" > .env
              echo "KAKAO_CLIENT_SECRET=${{ secrets.KAKAO_CLIENT_SECRET }}" >> .env
              echo "KAKAO_CALLBACK_URL=${{ secrets.KAKAO_CALLBACK_URL }}" >> .env

      # 4. Docker 이미지 빌드 및 Docker Hub로 푸시
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/nestjs-app:latest .
          echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/nestjs-app:latest

      # 5. .env 파일을 GCP VM에
      - name: Copy .env to GCP VM
        uses: appleboy/scp-action@v0.1.0 # 최신 버전으로 변경
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_PRIVATE_KEY }}
          source: ".env"
          target: "/home/${{ secrets.GCP_VM_USER }}/.env"  # GCP VM에서 사용할 경로

      # 6. GCP VM에 Docker 이미지 배포
      - name: Deploy to GCP VM
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_PRIVATE_KEY }}
          script: |
            # 기존 컨테이너 중지 및 제거
            docker stop nestjs-app || true
            docker rm nestjs-app || true
            
            # 최신 Docker 이미지 가져오기
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/nestjs-app:latest
            
            # .env 파일을 Docker 컨테이너에 전달하여 실행
            docker run -d \
              --name nestjs-app \
              -p 3000:3000 \
              --env-file /home/${{ secrets.GCP_VM_USER }}/.env \
              ${{ secrets.DOCKER_HUB_USERNAME }}/nestjs-app:latest
